### ISSUE TITLE
Make only the side where users are scrollabe. And fix the map.

### ISSUE THREAD

**Issue by dheerajdlalwani** [EddieJaoudeCommunity/EddieBotMap#1]

**Comment by srinath1412001** [comment]
@eddiejaoude  I think you fixed this problem.

**Comment by eddiejaoude** [comment]
@srinath1412001 you are right, this is now fixed. Thank you  @dheerajdlalwani for raising the issue and @srinath1412001 for the maintenance of the issues 👍 -  great team work 💪
