### ISSUE TITLE
Why the Repo is empty?

### ISSUE THREAD

**Issue by alrifay** [EddieJaoudeCommunity/EddieBotMap#15]
Please upload the project 😁

**Comment by stemount** [comment]
@alrifay No code, no bugs. ;)

haha, no but yes this does need some files 💯

**Comment by eddiejaoude** [comment]
You are right, thank you for the reminder 👍

**Comment by eddiejaoude** [comment]
Right I need to do this push 🤓

**Comment by eddiejaoude** [comment]
Pushed 🎉
