### ISSUE TITLE
Add Screenshot of the map in README

### ISSUE THREAD

**Issue by srinath1412001** [EddieJaoudeCommunity/EddieBotMap#18]
It would be great to have a screenshot of the map in the README section (even if its not the final version).

**Comment by eddiejaoude** [comment]
<img width="2834" alt="Screenshot 2020-08-04 at 00 02 43" src="https://user-images.githubusercontent.com/624760/89235454-1e8d6a00-d5e6-11ea-9c65-8f518b6be785.png">

**Comment by eddiejaoude** [comment]
Added to the README
